services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoomer-api
    depends_on:
      - db
    env_file: .env
    image: zoomer/api:v1.0.0
    ports:
      - "4000:4000"
  db:
    container_name: zoomer-db
    env_file: ./db/.env
    image: postgres:14-alpine
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DB_MOUNT}:/var/lib/postgresql/data

version: "3"
